export interface IFormElement {
  isCurrentElement: boolean,

  name: string,
  id: string,

  inputLabel?: string,
  inputPlaceholder?: string,
  inputWidth?: string,
  inputHeight?: string,
  inputRequired?: boolean,
  inputBorderStyle?: string,
  inputFontSize?: string,
  inputFontWeight?: string,
  inputColor?: string,

  buttonText?: string,
  buttonWidth?: string,
  buttonHeight?: string,
  buttonFontSize?: string,
  buttonFontWeight?: string,
  buttonColor?: string,
  buttonBackgroundColor?: string,

  textareaFieldText?: string,
  textareaPlaceholder?: string,
  textareaWidth?: string,
  textareaHeight?: string,
  textareaRequired?: boolean,
  textareaBorderStyle?: string,
  textareaFontSize?: string,
  textareaFontWeight?: string,
  textareaColor?: string,

  selectLabel?: string,
  selectWidth?: string,
  selectHeight?: string,
  selectRequired?: boolean,
  selectBorderStyle?: string,
  selectFontSize?: string,
  selectFontWeight?: string,
  selectColor?: string,
  
  checkboxFieldText?: string,
  checkboxLabel?: string,
  checkboxWidth?: string,
  checkboxHeight?: string,
  checkboxRequired?: boolean,
}

export interface IElementStyles {
  inputLabel?: string,
  inputPlaceholder?: string,
  inputWidth?: string,
  inputHeight?: string,
  inputRequired?: boolean,
  inputBorderStyle?: string,
  inputFontSize?: string,
  inputFontWeight?: string,
  inputColor?: string,
  
  buttonText?: string,
  buttonWidth?: string,
  buttonHeight?: string,
  buttonFontSize?: string,
  buttonFontWeight?: string,
  buttonColor?: string,
  buttonBackgroundColor?: string,

  textareaFieldText?: string,
  textareaPlaceholder?: string,
  textareaWidth?: string,
  textareaHeight?: string,
  textareaRequired?: boolean,
  textareaBorderStyle?: string,
  textareaFontSize?: string,
  textareaFontWeight?: string,
  textareaColor?: string,

  selectLabel?: string,
  selectWidth?: string,
  selectHeight?: string,
  selectRequired?: boolean,
  selectBorderStyle?: string,
  selectFontSize?: string,
  selectFontWeight?: string,
  selectColor?: string,
  
  checkboxFieldText?: string,
  checkboxLabel?: string,
  checkboxWidth?: string,
  checkboxHeight?: string,
  checkboxRequired?: boolean,
}

export interface IElementData {
  name: string,
  id: string,
}